CREATE TABLE "aluno" (
  "codigo" integer PRIMARY KEY NOT NULL,
  "nome" varchar(50) NOT NULL,
  "necessidadeespecial" boolean NOT NULL
);

CREATE TABLE "computador" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "descricao" varchar(200) NOT NULL
);

CREATE TABLE "monitor" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "descricao" varchar(200) NOT NULL
);

CREATE TABLE "vaga" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "codigo" char(7) UNIQUE NOT NULL,
  "computador_id" integer NOT NULL,
  "monitor_id" integer NOT NULL,
  "necessidadeespecial" boolean NOT NULL
);

CREATE TABLE "reserva" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "aluno_codigo" integer NOT NULL,
  "vaga_id" integer NOT NULL,
  "inicio" timestamp NOT NULL,
  "final" timestamp NOT NULL
);

ALTER TABLE "reserva" ADD FOREIGN KEY ("aluno_codigo") REFERENCES "aluno" ("codigo") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vaga" ADD FOREIGN KEY ("computador_id") REFERENCES "computador" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vaga" ADD FOREIGN KEY ("monitor_id") REFERENCES "monitor" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reserva" ADD FOREIGN KEY ("vaga_id") REFERENCES "vaga" ("id") DEFERRABLE INITIALLY IMMEDIATE;
