CREATE TABLE TBCLIENTE (
    CLICODIGO INTEGER NOT NULL PRIMARY KEY,
    CLINOME VARCHAR(200) NOT NULL,
    CLITIPO SMALLINT NOT NULL,
    CLIEMAIL VARCHAR(200),
    CLITELEFONE VARCHAR(40),
    CLILOGRADOURO VARCHAR(200),
    CIDCODIGO INTEGER NOT NULL
);

CREATE TABLE TBCIDADE (
    CIDCODIGO INTEGER NOT NULL PRIMARY KEY,
    CIDNOME VARCHAR(200) NOT NULL,
    CIDSIGLAUF VARCHAR NOT NULL
)